const translations = {
  pt: {
    mainTitle: "Transformamos projetos em soluções inteligentes.",
    mainDescription: "Com tecnologia e inovação, impulsionamos a construção do futuro.",
    linkAbout: "Quem somos",
    linkSolutions: "Soluções",
    linkClients: "Clientes",
    linkTeam: "Especialistas",
    linkContact: "Contato",
    aboutTitle: "Descubra por que somos referência em projetos e planejamento BIM",
    aboutDesc: "Somos especializados no desenvolvimento de projetos em BIM, consultoria técnica e planejamento estratégico voltados para o setor industrial, incluindo plantas, instalações e empreendimentos de grande porte.",
    stat1Title: "Mais eficiência nos projetos",
    stat1Text: "redução de retrabalhos e maior previsibilidade desde a concepção até a execução.",
    stat2Title: "+10 anos de experiência",
    stat2Text: "atuando em projetos de diversas escalas, com foco em qualidade e inovação.",
    stat3Title: "Modelagens BIM completas",
    stat3Text: "compatibilização de disciplinas, extração de quantitativos e simulação 4D e 5D.",
    stat4Title: "Consultorias personalizadas",
    stat4Text: "apoio estratégico para implementação de BIM e estruturação de processos construtivos.",
    service1Title: "Coordenação e Compatibilização",
    service1Text: "Oferecemos a gestão completa do ciclo de desenvolvimento de projetos, coordenando e compatibilizando desde a etapa inicial até a entrega final liberada para obra. Atuamos de forma integrada, promovendo a comunicação entre as equipes envolvidas e assegurando a eliminação de conflitos, a redução de retrabalho e o cumprimento rigoroso de prazos e padrões de qualidade.",
    service1Text2: "Oferecemos consultoria estratégica para a implantação e gestão de processos BIM, estruturando fluxos de trabalho, orientando a transformação digital e promovendo a integração entre equipes, tecnologia e objetivos de negócio.",
    service1Bloc1Title: "Desenvolvimento de Planos de Execução BIM (BEP/PEB)",
    service1Bloc1Text: "Estruturamos diretrizes personalizadas para nossos clientes a fim garantir a aplicação eficaz da metodologia BIM em todas as fases do projeto e garantir o sucesso do projeto.",
    service1Bloc2Title: "Configuração de Ambientes Colaborativos de Projeto",
    service1Bloc2Text: "Implantamos e estruturamos ambientes CDE (Common Data Environment) para projetos em BIM, garantindo segurança, organização e acessibilidade no compartilhamento e na gestão das informações ao longo do ciclo de vida do projeto.",
    service1Bloc3Title: "Padronização de entregáveis BIM",
    service1Bloc3Text: "Definimos nomenclaturas, estruturas de dados, templates, famílias e demais parâmetros técnicos para assegurar consistência e rastreabilidade nos modelos.",
    service1Bloc4Title: "Treinamentos técnicos e suporte contínuo às equipes",
    service1Bloc4Text: "Promovendo a capacitação e o alinhamento com os fluxos de trabalho definidos.",
    service1Bloc5Title: "Apoio na equalização técnica, processo de contratação e gestão das projetistas",
    service1Bloc5Text: "Atuamos diretamente na análise, validação técnica de propostas e gestão das projetistas, garantindo a aderência às exigências do projeto e às diretrizes BIM previamente definidas.",
    service1Bloc6Title: "Desenvolvimento de relatórios personalizados dos ambientes de projeto",
    service1Bloc6Text: "Elaboramos relatórios periódicos e estratégicos com indicadores de uso, desempenho e organização das plataformas colaborativas, contribuindo para o controle, rastreamento e tomada de decisão ao longo do projeto.",
    service2Title: "Modelagem BIM",
    service2Text: "Desenvolvemos modelos digitais inteligentes e multidisciplinares que asseguram consistência, confiabilidade e total aderência à realidade da obra. Nossos modelos são elaborados com alto nível de precisão geométrica e organizados de acordo com as melhores práticas internacionais de modelagem da informação da construção (BIM).",
    service2Text2: "Atuamos em todas as disciplinas do projeto — arquitetura, estruturas, instalações, infraestrutura, processos industriais, entre outras — garantindo a integração entre as áreas e a rastreabilidade das informações ao longo de todo o ciclo de vida do empreendimento.",
    service2Bloc1Title: "Fidelidade à obra real",
    service2Bloc1Text: "Modelos digitais inteligentes e construtivos, desenvolvidos para representar com precisão a realidade da obra. Utilizamos escaneamentos 3D quando necessário, além de seguir os projetos executivos e atender às exigências específicas de cada cliente.",
    service2Bloc2Title: "Precisão técnica e geométrica",
    service2Bloc2Text: "Garantimos precisão técnica nos modelos, tanto em termos de geometria quanto de informações, ajustando o nível de detalhamento conforme a fase do projeto — desde os estudos iniciais até a execução e operação — sempre de acordo com as necessidades do cliente e dos objetivos de uso.",
    service2Bloc3Title: "Modelos orientados a dados",
    service2Bloc3Text: "Estruturamos os elementos com atributos e parâmetros específicos, permitindo a extração de informações automáticas e a conexão com outras ferramentas, como cronogramas (4D), orçamentos (5D) e sistemas de manutenção (6D).",
    service2Bloc4Title: "Interoperabilidade e compatibilidade",
    service2Bloc4Text: "Garantimos interoperabilidade e compatibilidade ao adotar ferramentas amplamente utilizadas no setor, com foco na integração entre diferentes disciplinas por meio de formatos abertos, como o IFC, e outras normas reconhecidas para troca de informações em ambientes colaborativos.",
    service2Bloc5Title: "Suporte à tomada de decisão",
    service2Bloc5Text: "Os modelos servem como base confiável para análises de interferência (clash detection), planejamento, sequenciamento de obras e controle de custos.",
    service2Bloc6Title: "Divisão estratégica segundo a metodologia AWP",
    service2Bloc6Text: "Estruturamos os modelos com base na metodologia Advanced Work Packaging, organizando pacotes de trabalho (CWP, EWP, IWP)desde a fase de engenharia, garantindo integração com planejamento, suprimentos e execução. Essa abordagem permite maior controle, previsibilidade e eficiência nas frentes de obra.",
    service3Title: "Planejamento e Controle 4D",
    service3Text: "Planejamos e controlamos sua obra de forma integrada, utilizando modelos BIM vinculados ao cronograma executivo, por meio de metodologias avançadas como 4D BIM, AWP (Advanced Work Packaging), entre outras.",
    service3Text2: "Essa abordagem permite simulações visuais do progresso da obra, facilitando a compreensão do sequenciamento das atividades, a identificação de interferências temporais e a antecipação de riscos. Combinando o modelo tridimensional com o planejamento temporal, proporcionamos uma visão clara e estratégica do canteiro ao longo do tempo.",
    service3Bloc1Title: "Simulações 4D interativas",
    service3Bloc1Text: "Visualização da execução da obra ao longo do tempo, com base em pacotes de trabalho, frentes de serviço e áreas produtivas.",
    service3Bloc2Title: "Integração com a metodologia AWP",
    service3Bloc2Text: "Organização do planejamento por pacotes (CWP, EWP, IWP), permitindo maior controle e previsibilidade dasentregas de engenharia, suprimentos e construção.",
    service3Bloc3Title: "Tomada de decisão mais precisa",
    service3Bloc3Text: "A combinação de cronograma e modelo BIM proporciona análises mais assertivas, maior capacidade de reação a desvios e melhor uso dos recursos.",
    service3Bloc4Title: "Comunicação eficiente com stakeholders",
    service3Bloc4Text: "Apresentações visuais facilitam o entendimento entre todas as partes envolvidas, promovendo alinhamento entre obra, engenharia, gestão e contratados.",
    service4Title: "Quantitativos e Orçamento 5D",
    service4Text: "Estruturamos os modelos BIM de forma estratégica para permitir a extração precisa e automatizada de quantitativos, alinhados à Estrutura Analítica do Projeto (EAP) ou ao plano de contas do cliente. Essa organização garante padronização, rastreabilidade e confiabilidade das informações extraídas diretamente do modelo.",
    service4Text2: "A partir dos dados obtidos, desenvolvemos orçamentos inteligentes e atualizáveis, que permanecem conectados ao modelo ao longo do ciclo de vida do projeto. Isso permite que qualquer alteração no projeto reflita automaticamente nas estimativas de custo, promovendo maior controle e transparência nos investimentos",
    service4Bloc1Title: "Modelos preparados para medição automatizada",
    service4Bloc1Text: "Utilização de parâmetros, filtros e codificações que facilitam a segmentação e o agrupamento dos elementos conforme a lógica orçamentária.",
    service4Bloc2Title: "Orçamentos dinâmicos e conectados ao BIM",
    service4Bloc2Text: "Atualizações automáticas dos quantitativos em caso de mudanças no projeto, garantindo agilidade e precisão na revisão de custos.",
    service4Bloc3Title: "Rastreabilidade total",
    service4Bloc3Text: "Cada item orçado está vinculado diretamente a elementos do modelo, permitindo auditorias, simulações e tomadas de decisão com base em dados consistentes.",
    service4Bloc4Title: "Compatibilidade com plataformas de orçamento e controle",
    service4Bloc4Text: "Exportamos os dados para softwares como Excel, Power BI, e ferramentas de custo e planejamento adotadas pelo cliente.",
    service5Title: "Laser Scanning e Modelagem As-Built",
    service5Text: "Utilizamos tecnologia de ponta em escaneamento a laser 3D (Laser Scanning) para capturar com precisão milimétrica as condições reais da sua construção. A partir desses dados, desenvolvemos modelos digitais inteligentes (Scan to BIM) que refletem fielmente o estado atual da edificação ou infraestrutura.",
    service5Text2: "Realizamos modelagem 3D a partir de nuvens de pontos, garantindo alta fidelidade à obra existente. Essa abordagem permite a criação de modelos digitais precisos e atualizados, ideais para retrofit, as built e gestão de ativos.",
    service5Bloc1Title: "Levantamento preciso e não invasivo",
    service5Bloc1Text: "Captura de milhões de pontos por segundo, reduzindo a necessidade de visitas de campo e eliminando erros de medição manual.",
    service5Bloc2Title: "Base para retrofit, manutenção e expansão",
    service5Bloc2Text: "Ideal para obras existentes que precisam de atualização de documentação, planejamento de obras de intervenção ou análise de viabilidade.",
    service5Bloc3Title: "Apoio à tomada de decisão técnica",
    service5Bloc3Text: "Acesso a informações confiáveis e visuais sobre o estado atual da construção para apoiar decisões estratégicas.",
    service6Title: "Consultoria e Treinamentos",
    service6Text: "Apoiamos empresas na implementação, estruturação e evolução da metodologia BIM, oferecendo uma consultoria estratégica que integra tecnologia, pessoas e processos. Atuamos lado a lado com sua equipe para transformar o BIM em um verdadeiro diferencial competitivo, alinhado aos objetivos do negócio e às necessidades do projeto.",
    service6Text2: "Além da consultoria técnica, oferecemos treinamentos personalizadosque capacitam profissionais de diferentes níveis — da liderança à operação — promovendo autonomia, alinhamento e eficiência na adoção de novas ferramentas e fluxos de trabalho.",
    service6Bloc1Title: "Diagnóstico de maturidade BIM",
    service6Bloc1Text: "Definição de roadmap de implantação.",
    service6Bloc2Title: "Criação de diretrizes e planos de execução BIM (BEP/PEB)",
    service6Bloc2Text: "Alinhados à realidade da empresa e dos projetos.",
    service6Bloc3Title: "Definição de processos e fluxos de informação",
    service6Bloc3Text: "Entre áreas como engenharia, planejamento, suprimentos e obra.",
    service6Bloc4Title: "Treinamentos práticos e estratégicos",
    service6Bloc4Text: "Presenciais ou online, com foco em ferramentas, processos e tomada de decisão baseada em modelos.",
    service6Bloc5Title: "Apoio contínuo na evolução da maturidade BIM",
    service6Bloc6Title: "Templates e padrões",
    service6Bloc6Text: "Desenvolvemos padrões e templates personalizados para softwares BIM, garantindo uniformidade na modelagem, consistência nas informações e maior eficiência nos processos de projeto e coordenação.",
    whoUsed: "Quem utilizou este serviço",
    service6Bloc5Text: "com acompanhamento, auditoria de modelos, padronizações e orientações técnicas.",
    clientsTitle: "Alguns de nossos clientes e seus principais projetos",
    clientGerdau: "Coordenação e gestão de projeto de implementação do Shredder Gerdau, está sendo implementando um novo setor de reciclagem na unidade de Pindamonhangaba (SP), que contará com um equipamento conhecido como Shredder. Esse investimento faz parte de um programa global de expansão, com previsão de R$ 354 milhões destinados ao setor de reciclagem, visando a implantação de tecnologias avançadas para a separação de materiais e redução do impacto ambiental das operações.",
    clientHead5: "Consultoria e implementação de processos BIM para o setor de energia, mineração, infraestrutura, prestações de serviço de modelagem, gestão e coordenação.",
    clienteUsiminas: "Coordenação e gestão de projeto de Modernização Alto-Forno 3 Usiminas, localizado na usina de Ipatinga (MG), foi oficialmente reinaugurado em 24 de janeiro de 2024, após uma ampla reforma que demandou um investimento de R$ 2,7 bilhões. Esse equipamento é o maior da companhia e responde por cerca de 70% da produção de aço bruto da unidade.",
    clienteHorizonte: "Coordenação e gestão do projeto Araguaia Ferro Nickel – Horizonte Minerals, é um empreendimento de mineração de níquel localizado em Conceição do Araguaia, no sudeste do Pará, Brasil, com investimento de R$ 2,9 bilhões. Concebido para ser uma das principais minas de ferroníquel do país, o projeto visava atender à crescente demanda global por níquel, especialmente para a produção de aço inoxidável e baterias de veículos elétricos.",
    clientDraft: "Consultoria e implementação de processos BIM para o setor de mineração e infraestrutura e prestações de serviço de modelagem, gestão e coordenação.",
    clientArcelor: "Coordenação e gestão do projeto do novo laminador de perfis da ArcelorMittal em Barra Mansa. Com investimento de R$ 1,3 bilhão, o projeto ampliará significativamente a capacidade produtiva da planta, atendendo aos setores de construção civil, energia e indústria automotiva. Nossos serviços contribuíram para a modernização da infraestrutura industrial, promovendo maior eficiência operacional e suporte ao crescimento sustentável da companhia.",
    teamtTitle: "Nosso time de especialistas",
    team1position: "(Diretor)",
    team1Text: "Especialista em BIM com ampla experiência na coordenação, gestão e implementação de processos digitais em projetos complexos de grande porte. Atuou em empreendimentos estratégicos como a modernização do Alto-Forno 3 da Usiminas (Ipatinga/MG), implementação do Shredder Gerdau (Pindamonhangaba/SP), laminador de perfis da ArcelorMittal (Barra Mansa/RJ) e Projeto Araguaia da Horizonte Minerals (Pará), totalizando mais de R$ 7 bilhões em investimentos. Com sólida atuação em setores como mineração, siderurgia, energia e reciclagem industrial, lidera a implantação de metodologias BIM aplicadas à modelagem multidisciplinar, planejamento 4D, integração com cronogramas, extração de quantitativos e suporte à tomada de decisão. Por meio de consultorias prestadas à HEAD5 Engenharia, Draft Solutions dentre outras, viabiliza a digitalização de projetos com foco em eficiência, rastreabilidade e padronização.",
    footerInstitutional: "Institucional",
    footerAbout: "Sobre nós",
    footerTeam: "Nosso time",
    footerSolutions: "Soluções",
    footerCompat: "Coordenação e Compatibilização",
    footerBim: "Modelagem BIM",
    footer4d: "Planejamento e Controle 4D",
    footer5d: "Quantitativos e Orçamento 5D",
    footerCloud: "Laser Scanning e Modelagem As-Built",
    footerConsulting: "Consultoria e Treinamentos",
    footerLegal: "Legal",
    footerPrivacy: "Política de Privacidade",
    footerTerms: "Termos de Uso",
    footerContactTitle: "Fale conosco",
    footerPhone: "+55 (31) 98396-4334",
    footerEmail: "joao.hamacek@voxcs.com.br",
    footerCopy: "© 2025 Vox. Todos os direitos reservados",
    learnMoreButton: "Saiba mais",
    termsTitle: "Política de Privacidade",
    termsDescription: "Sua privacidade é importante para nós. Esta política explica como coletamos, usamos e protegemos suas informações.",
    terms1Title: "1. Aceitação dos Termos",
    terms1Text: "Ao acessar ou usar este site, você concorda com estes Termos de Uso e com todas as leis e regulamentos aplicáveis.",
    terms2Title: "2. Uso do Site",
    terms2Text: "Você se compromete a utilizar o site de forma ética e legal, respeitando os direitos da Vox e de terceiros.",
    terms3Title: "3. Alterações",
    terms3Text: "A Vox pode alterar estes Termos de Uso a qualquer momento, sem aviso prévio.",
    privacy1Title: "1. Coleta de Informações",
    privacy1Text: "Coletamos informações fornecidas por você e dados de navegação para melhorar sua experiência.",
    privacy2Title: "2. Uso das Informações",
    privacy2Text: "Utilizamos suas informações apenas para fins internos e não as compartilhamos com terceiros sem sua autorização.",
    privacy3Title: "3. Segurança",
    privacy3Text: "Adotamos medidas de segurança para proteger seus dados pessoais.",
    privacyTermsBackButton: "Voltar para o site",
    contactTitle: "Fale conosco",
    contactText: "Tem dúvidas, sugestões ou deseja saber mais sobre nossos serviços? Preencha o formulário abaixo e nossa equipe retornará o mais breve possível.",
    contactName: "Nome",
    contactMail: "E-mail",
    contactMessage: "Mensagem",
    contactSend: "Enviar",
    successTitle: "Mensagem enviada!",
    successText: "Obrigado pelo contato. Em breve nossa equipe retornará para você."
  },
  
  en: {
    mainTitle: "We transform projects into intelligent solutions.",
    mainDescription: "With technology and innovation, we drive the construction of the future.",
    linkAbout: "About us",
    linkSolutions: "Solutions",
    linkClients: "Clients",
    linkTeam: "Specialists",
    linkContact: "Contact",
    aboutTitle: "Discover why we are a reference in BIM design and planning",
    aboutDesc: "We specialize in BIM project development, technical consulting and strategic planning for the industrial sector, covering plants, facilities and large‑scale ventures.",
    stat1Title: "More efficient projects",
    stat1Text: "less rework and greater predictability from design to execution.",
    stat2Title: "+10 years of experience",
    stat2Text: "working on projects of all scales, with a focus on quality and innovation.",
    stat3Title: "Complete BIM modeling",
    stat3Text: "discipline coordination, quantity takeoffs, and 4D/5D simulation.",
    stat4Title: "Customized consulting",
    stat4Text: "strategic support for BIM implementation and construction process structuring.",
    service1Title: "Coordination and Compatibility",
    service1Text: "We offer complete management of the project development cycle, coordinating and aligning all disciplines from the initial stage to the final delivery ready for construction. We work in an integrated manner, promoting communication among the teams involved and ensuring the elimination of conflicts, reduction of rework, and strict adherence to deadlines and quality standards.",
    service1Text2: "We offer strategic consulting for the implementation and management of BIM processes, structuring workflows, guiding digital transformation, and promoting integration between teams, technology, and business objectives.",
    service1Bloc1Title: "Development of BIM Execution Plans (BEP/PEB)",
    service1Bloc1Text: "We structure customized guidelines for our clients to ensure the effective application of the BIM methodology throughout all project phases and ensure its success.",
    service1Bloc2Title: "Configuration of Collaborative Project Environments",
    service1Bloc2Text: "We implement and structure CDE (Common Data Environment) platforms for BIM projects, ensuring security, organization, and accessibility in information sharing and management throughout the project lifecycle.",
    service1Bloc3Title: "Standardization of BIM Deliverables",
    service1Bloc3Text: "We define naming conventions, data structures, templates, families, and other technical parameters to ensure consistency and traceability in the models.",
    service1Bloc4Title: "Technical Training and Ongoing Team Support",
    service1Bloc4Text: "Promoting capacity building and alignment with defined workflows.",
    service1Bloc5Title: "Support in Technical Equalization, Contracting Process, and Management of Designers",
    service1Bloc5Text: "We act directly in the analysis and technical validation of proposals and in managing the designers, ensuring adherence to the project requirements and previously defined BIM guidelines.",
    service1Bloc6Title: "Development of Customized Reports for Project Environments",
    service1Bloc6Text: "We prepare periodic and strategic reports with usage, performance, and organization indicators of collaborative platforms, contributing to control, traceability, and decision-making throughout the project.",
    service2Title: "BIM Modeling",
    service2Text: "We develop intelligent and multidisciplinary digital models that ensure consistency, reliability, and full adherence to the reality of the construction site. Our models are created with a high level of geometric accuracy and structured according to international best practices in Building Information Modeling (BIM).",
    service2Text2: "We work across all project disciplines — architecture, structures, MEP, infrastructure, industrial processes, and more — ensuring integration between areas and traceability of information throughout the entire project lifecycle.",
    service2Bloc1Title: "Faithfulness to the real construction",
    service2Bloc1Text: "Intelligent and constructible digital models developed to accurately represent the reality of the construction. We use 3D scanning when necessary, in addition to following executive project plans and meeting each client's specific requirements.",
    service2Bloc2Title: "Technical and geometric precision",
    service2Bloc2Text: "We ensure technical accuracy in the models, both in terms of geometry and information, adjusting the level of detail according to the project phase — from early studies to execution and operation — always aligned with the client’s needs and intended use.",
    service2Bloc3Title: "Data-driven models",
    service2Bloc3Text: "We structure elements with specific attributes and parameters, enabling automated data extraction and integration with other tools such as schedules (4D), budgets (5D), and maintenance systems (6D).",
    service2Bloc4Title: "Interoperability and compatibility",
    service2Bloc4Text: "We ensure interoperability and compatibility by adopting widely used tools in the industry, focusing on the integration between different disciplines through open formats such as IFC and other recognized standards for information exchange in collaborative environments.",
    service2Bloc5Title: "Decision-making support",
    service2Bloc5Text: "Models serve as a reliable foundation for clash detection, planning, construction sequencing, and cost control.",
    service2Bloc6Title: "Strategic division according to AWP methodology",
    service2Bloc6Text: "We structure the models based on the Advanced Work Packaging (AWP) methodology, organizing work packages (CWP, EWP, IWP) from the engineering phase, ensuring integration with planning, procurement, and execution. This approach enables greater control, predictability, and efficiency on the construction front.",
    service3Title: "4D Planning and Control",
    service3Text: "We plan and control your project in an integrated manner, using BIM models linked to the executive schedule through advanced methodologies such as 4D BIM, AWP (Advanced Work Packaging), among others.",
    service3Text2: "This approach enables visual simulations of construction progress, facilitating the understanding of activity sequencing, identification of temporal clashes, and anticipation of risks. By combining the 3D model with the project timeline, we provide a clear and strategic vision of the site over time.",
    service3Bloc1Title: "Interactive 4D simulations",
    service3Bloc1Text: "Visualization of construction execution over time, based on work packages, work fronts, and productive areas.",
    service3Bloc2Title: "Integration with AWP methodology",
    service3Bloc2Text: "Planning organized by packages (CWP, EWP, IWP), allowing greater control and predictability of engineering, procurement, and construction deliveries.",
    service3Bloc3Title: "More accurate decision-making",
    service3Bloc3Text: "The combination of schedule and BIM model allows for more assertive analysis, better responsiveness to deviations, and improved resource utilization.",
    service3Bloc4Title: "Efficient communication with stakeholders",
    service3Bloc4Text: "Visual presentations facilitate understanding among all involved parties, promoting alignment between construction, engineering, management, and contractors.",
    service4Title: "5D Quantities and Cost Estimation",
    service4Text: "We strategically structure BIM models to enable the accurate and automated extraction of quantities, aligned with the Project Work Breakdown Structure (WBS) or the client’s cost breakdown plan. This organization ensures standardization, traceability, and reliability of the information extracted directly from the model.",
    service4Text2: "Based on the obtained data, we develop smart and updatable budgets that remain connected to the model throughout the project lifecycle. This allows any project changes to automatically reflect in the cost estimates, ensuring greater control and investment transparency.",
    service4Bloc1Title: "Models prepared for automated quantity takeoff",
    service4Bloc1Text: "Use of parameters, filters, and codifications that facilitate the segmentation and grouping of elements according to the budgeting logic.",
    service4Bloc2Title: "Dynamic budgets connected to BIM",
    service4Bloc2Text: "Automatic updates of quantities in case of project changes, ensuring agility and accuracy in cost review.",
    service4Bloc3Title: "Full traceability",
    service4Bloc3Text: "Each budgeted item is directly linked to model elements, allowing audits, simulations, and decision-making based on consistent data.",
    service4Bloc4Title: "Compatibility with budgeting and control platforms",
    service4Bloc4Text: "We export the data to software such as Excel, Power BI, and other cost and planning tools used by the client.",
    service5Title: "Laser Scanning and As-Built Modeling",
    service5Text: "We use cutting-edge 3D laser scanning technology to capture the real conditions of your construction with millimeter precision. From this data, we develop intelligent digital models (Scan to BIM) that faithfully reflect the current state of the building or infrastructure.",
    service5Text2: "We perform 3D modeling from point clouds, ensuring high fidelity to the existing construction. This approach enables the creation of accurate and up-to-date digital models, ideal for retrofit, as-built documentation, and asset management.",
    service5Bloc1Title: "Accurate and non-invasive surveying",
    service5Bloc1Text: "Captures millions of points per second, reducing the need for site visits and eliminating manual measurement errors.",
    service5Bloc2Title: "Basis for retrofit, maintenance, and expansion",
    service5Bloc2Text: "Ideal for existing buildings requiring documentation updates, intervention planning, or feasibility analysis.",
    service5Bloc3Title: "Support for technical decision-making",
    service5Bloc3Text: "Access to reliable and visual information about the current state of the construction to support strategic decisions.",
    service6Title: "Consulting and Training",
    service6Text: "We support companies in the implementation, structuring, and advancement of the BIM methodology, offering strategic consulting that integrates technology, people, and processes. We work side by side with your team to turn BIM into a true competitive advantage, aligned with business objectives and project needs.",
    service6Text2: "In addition to technical consulting, we offer personalized training that empowers professionals at all levels — from leadership to operations — promoting autonomy, alignment, and efficiency in adopting new tools and workflows.",
    service6Bloc1Title: "BIM maturity assessment",
    service6Bloc1Text: "and definition of the implementation roadmap.",
    service6Bloc2Title: "Creation of BIM Execution Plans (BEP/PEB)",
    service6Bloc2Text: "aligned with the company's and project's reality.",
    service6Bloc3Title: "Definition of processes and information flows",
    service6Bloc3Text: "between areas such as engineering, planning, procurement, and construction.",
    service6Bloc4Title: "Practical and strategic training",
    service6Bloc4Text: "delivered in-person or online, focusing on tools, processes, and model-based decision-making.",
    service6Bloc5Title: "Ongoing support in BIM maturity development",
    service6Bloc6Title: "Templates and standards",
    service6Bloc6Text: "We develop customized standards and templates for BIM software, ensuring modeling uniformity, information consistency, and greater efficiency in design and coordination processes.",
    whoUsed: "Who used this service",
    service6Bloc5Text: "through monitoring, model audits, standardization, and technical guidance.",
    clientsTitle: "Some of our clients and their key projects",
    clientGerdau: "Project coordination and management for the implementation of Gerdau's Shredder. A new recycling sector is being implemented at the Pindamonhangaba (SP) plant, which will feature equipment known as a Shredder. This investment is part of a global expansion program, with an estimated R$ 354 million allocated to the recycling sector, aiming to implement advanced technologies for material separation and reduce the environmental impact of operations.",
    clientHead5: "Consulting and implementation of BIM processes for the energy, mining, and infrastructure sectors, including modeling, management, and coordination services.",
    clienteUsiminas: "Project coordination and management for the modernization of Blast Furnace 3 at Usiminas, located at the Ipatinga (MG) plant. It was officially reopened on January 24, 2024, after a major overhaul that required an investment of R$ 2.7 billion. This equipment is the company’s largest and accounts for approximately 70% of the unit’s crude steel production.",
    clienteHorizonte: "Coordination and management of the Araguaia Ferro Nickel project – Horizonte Minerals. This nickel mining venture is located in Conceição do Araguaia, in southeastern Pará, Brazil, with an investment of R$ 2.9 billion. Designed to be one of the country’s main ferronickel mines, the project aimed to meet the growing global demand for nickel, especially for stainless steel production and electric vehicle batteries.",
    clientDraft: "Consulting and implementation of BIM processes for the mining and infrastructure sectors, including modeling, management, and coordination services.",
    clientArcelor: "Coordination and management of the project for the new profile rolling mill at ArcelorMittal in Barra Mansa. With an investment of R$ 1.3 billion, the project will significantly increase the plant’s production capacity, serving the civil construction, energy, and automotive sectors. Our services contributed to the modernization of the industrial infrastructure, promoting greater operational efficiency and supporting the company's sustainable growth.",
    teamtTitle: "Our team of specialists",
    team1position: "(Director)",
    team1Text: "BIM specialist with extensive experience in coordinating, managing, and implementing digital processes in large-scale and complex projects. Has worked on strategic ventures such as the modernization of Blast Furnace 3 at Usiminas (Ipatinga/MG), implementation of the Shredder at Gerdau (Pindamonhangaba/SP), profile rolling mill at ArcelorMittal (Barra Mansa/RJ), and the Araguaia Project by Horizonte Minerals (Pará), totaling over R$ 7 billion in managed investments. With solid performance in sectors such as mining, steelmaking, energy, and industrial recycling, leads the implementation of BIM methodologies applied to multidisciplinary modeling, 4D planning, schedule integration, quantity takeoffs, and decision-making support. Through consulting services provided to HEAD5 Engenharia, Draft Solutions, among others, enables the digitalization of projects with a focus on efficiency, traceability, and standardization.",
    footerInstitutional: "Institutional",
    footerAbout: "About us",
    footerTeam: "Our team",
    footerSolutions: "Solutions",
    footerCompat: "Coordination and Compatibility",
    footerBim: "Modelagem BIM",
    footer4d: "4D Planning and Control",
    footer5d: "5D Quantities and Cost Estimation",
    footerCloud: "Laser Scanning and As-Built Modeling",
    footerConsulting: "Consulting and Training",
    footerLegal: "Legal",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Use",
    footerContactTitle: "Contact us",
    footerPhone: "+55 (31) 98396-4334",
    footerEmail: "joao.hamacek@voxcs.com.br",
    footerCopy: "© 2025 Vox. All rights reserved.",
    learnMoreButton: "Learn more",
    termsTitle: "Privacy Policy",
    termsDescription: "Your privacy is important to us. This policy explains how we collect, use, and protect your information.",
    terms1Title: "1. Acceptance of Terms",
    terms1Text: "By accessing or using this website, you agree to these Terms of Use and all applicable laws and regulations.",
    terms2Title: "2. Use of the Website",
    terms2Text: "You agree to use the website ethically and legally, respecting the rights of Vox and third parties.",
    terms3Title: "3. Changes",
    terms3Text: "Vox may modify these Terms of Use at any time without prior notice.",
    privacy1Title: "1. Information Collection",
    privacy1Text: "We collect information provided by you and browsing data to enhance your experience.",
    privacy2Title: "2. Use of Information",
    privacy2Text: "We use your information for internal purposes only and do not share it with third parties without your consent.",
    privacy3Title: "3. Security",
    privacy3Text: "We implement security measures to protect your personal data.",
    privacyTermsBackButton: "Back to the website",
    contactTitle: "Contact us",
    contactText: "Have questions, suggestions, or want to know more about our services? Fill out the form below and our team will get back to you as soon as possible.",
    contactName: "Name",
    contactMail: "Email",
    contactMessage: "Message",
    contactSend: "Send",
    successTitle: "Message sent!",
    successText: "Thank you for reaching out. Our team will get back to you shortly."
  },

  es: {
    mainTitle: "Transformamos proyectos en soluciones inteligentes.",
    mainDescription: "Con tecnología e innovación, impulsamos la construcción del futuro.",
    linkAbout: "Quiénes somos",
    linkSolutions: "Soluciones",
    linkClients: "Clientes",
    linkTeam: "Especialistas",
    linkContact: "Contacto",
    aboutTitle: "Descubre por qué somos una referencia en proyectos y planificación BIM",
    aboutDesc: "Estamos especializados en el desarrollo de proyectos BIM, consultoría técnica y planificación estratégica para el sector industrial, incluidas plantas, instalaciones y emprendimientos de gran envergadura.",
    stat1Title: "Más eficiencia en los proyectos",
    stat1Text: "reducción de retrabajos y mayor previsibilidad desde la concepción hasta la ejecución.",
    stat2Title: "+10 años de experiencia",
    stat2Text: "actuando en proyectos de diversas escalas, con enfoque en calidad e innovación.",
    stat3Title: "Modelados BIM completos",
    stat3Text: "coordinación de disciplinas, extracción de cantidades y simulación 4D y 5D.",
    stat4Title: "Consultorías personalizadas",
    stat4Text: "apoyo estratégico para la implementación de BIM y estructuración de procesos constructivos.",
    service1Title: "Coordinación y Compatibilización",
    service1Text: "Ofrecemos la gestión completa del ciclo de desarrollo de proyectos, coordinando y compatibilizando todas las disciplinas desde la etapa inicial hasta la entrega final lista para la obra. Actuamos de forma integrada, promoviendo la comunicación entre los equipos involucrados y asegurando la eliminación de conflictos, la reducción de retrabajos y el estricto cumplimiento de los plazos y estándares de calidad.",
    service2Title: "Modelado BIM",
    service1Text2: "Ofrecemos consultoría estratégica para la implementación y gestión de procesos BIM, estructurando flujos de trabajo, orientando la transformación digital y promoviendo la integración entre equipos, tecnología y objetivos de negocio.",
    service1Bloc1Title: "Desarrollo de Planes de Ejecución BIM (PEB/BEP)",
    service1Bloc1Text: "Estructuramos directrices personalizadas para nuestros clientes con el fin de garantizar la aplicación eficaz de la metodología BIM en todas las fases del proyecto y asegurar su éxito.",
    service1Bloc2Title: "Configuración de Entornos Colaborativos de Proyecto",
    service1Bloc2Text: "Implementamos y estructuramos entornos CDE (Common Data Environment) para proyectos en BIM, garantizando seguridad, organización y accesibilidad en el intercambio y gestión de la información a lo largo del ciclo de vida del proyecto.",
    service1Bloc3Title: "Estandarización de Entregables BIM",
    service1Bloc3Text: "Definimos nomenclaturas, estructuras de datos, plantillas, familias y demás parámetros técnicos para asegurar la consistencia y trazabilidad en los modelos.",
    service1Bloc4Title: "Capacitación Técnica y Soporte Continuo a los Equipos",
    service1Bloc4Text: "Promoviendo la formación y el alineamiento con los flujos de trabajo definidos.",
    service1Bloc5Title: "Apoyo en la Igualación Técnica, Contratación y Gestión de Proyectistas",
    service1Bloc5Text: "Actuamos directamente en el análisis, validación técnica de propuestas y gestión de los proyectistas, garantizando la adherencia a los requerimientos del proyecto y a las directrices BIM previamente definidas.",
    service1Bloc6Title: "Desarrollo de Informes Personalizados de los Entornos de Proyecto",
    service1Bloc6Text: "Elaboramos informes periódicos y estratégicos con indicadores de uso, rendimiento y organización de las plataformas colaborativas, contribuyendo al control, trazabilidad y toma de decisiones a lo largo del proyecto.",
    service2Text: "Desarrollamos modelos digitales inteligentes y multidisciplinarios que garantizan consistencia, confiabilidad y total adherencia a la realidad de la obra. Nuestros modelos se elaboran con un alto nivel de precisión geométrica y se organizan de acuerdo con las mejores prácticas internacionales de modelado de información de la construcción (BIM).",
    service2Text2: "Actuamos en todas las disciplinas del proyecto — arquitectura, estructuras, instalaciones, infraestructura, procesos industriales, entre otras — garantizando la integración entre áreas y la trazabilidad de la información a lo largo de todo el ciclo de vida del emprendimiento.",
    service2Bloc1Title: "Fidelidad a la obra real",
    service2Bloc1Text: "Modelos digitales inteligentes y constructivos, desarrollados para representar con precisión la realidad de la obra. Utilizamos escaneos 3D cuando es necesario, además de seguir los proyectos ejecutivos y cumplir con los requisitos específicos de cada cliente.",
    service2Bloc2Title: "Precisión técnica y geométrica",
    service2Bloc2Text: "Garantizamos precisión técnica en los modelos, tanto en geometría como en información, ajustando el nivel de detalle según la fase del proyecto — desde los estudios iniciales hasta la ejecución y operación — siempre de acuerdo con las necesidades del cliente y los objetivos de uso.",
    service2Bloc3Title: "Modelos orientados a datos",
    service2Bloc3Text: "Estructuramos los elementos con atributos y parámetros específicos, lo que permite la extracción automática de información y su conexión con otras herramientas, como cronogramas (4D), presupuestos (5D) y sistemas de mantenimiento (6D).",
    service2Bloc4Title: "Interoperabilidad y compatibilidad",
    service2Bloc4Text: "Garantizamos la interoperabilidad y compatibilidad mediante el uso de herramientas ampliamente utilizadas en el sector, con enfoque en la integración entre diferentes disciplinas a través de formatos abiertos como IFC y otras normas reconocidas para el intercambio de información en entornos colaborativos.",
    service2Bloc5Title: "Apoyo a la toma de decisiones",
    service2Bloc5Text: "Los modelos sirven como base confiable para análisis de interferencias (clash detection), planificación, secuenciación de obras y control de costos.",
    service2Bloc6Title: "División estratégica según la metodología AWP",
    service2Bloc6Text: "Estructuramos los modelos con base en la metodología Advanced Work Packaging, organizando paquetes de trabajo (CWP, EWP, IWP) desde la fase de ingeniería, garantizando integración con la planificación, suministros y ejecución. Este enfoque permite mayor control, previsibilidad y eficiencia en los frentes de obra.",
    service3Title: "Planificación y Control 4D",
    service3Text: "Planificamos y controlamos su obra de forma integrada, utilizando modelos BIM vinculados al cronograma ejecutivo mediante metodologías avanzadas como 4D BIM, AWP (Advanced Work Packaging), entre otras.",
    service3Text2: "Este enfoque permite simulaciones visuales del progreso de la obra, facilitando la comprensión de la secuencia de actividades, la identificación de interferencias temporales y la anticipación de riesgos. Al combinar el modelo tridimensional con la planificación temporal, proporcionamos una visión clara y estratégica del sitio a lo largo del tiempo.",
    service3Bloc1Title: "Simulaciones 4D interactivas",
    service3Bloc1Text: "Visualización de la ejecución de la obra a lo largo del tiempo, basada en paquetes de trabajo, frentes de servicio y áreas productivas.",
    service3Bloc2Title: "Integración con la metodología AWP",
    service3Bloc2Text: "Organización de la planificación por paquetes (CWP, EWP, IWP), permitiendo un mayor control y previsibilidad en las entregas de ingeniería, suministros y construcción.",
    service3Bloc3Title: "Toma de decisiones más precisa",
    service3Bloc3Text: "La combinación del cronograma y el modelo BIM permite análisis más asertivos, mayor capacidad de respuesta ante desviaciones y un mejor uso de los recursos.",
    service3Bloc4Title: "Comunicación eficiente con stakeholders",
    service3Bloc4Text: "Las presentaciones visuales facilitan la comprensión entre todas las partes involucradas, promoviendo la alineación entre obra, ingeniería, gestión y contratistas.",
    service4Title: "Cantidades y Presupuestos 5D",
    service4Text: "Estructuramos los modelos BIM de forma estratégica para permitir la extracción precisa y automatizada de cantidades, alineadas con la Estructura de Desglose del Proyecto (EDP) o con el plan de cuentas del cliente. Esta organización garantiza la estandarización, trazabilidad y confiabilidad de la información extraída directamente del modelo.",
    service4Text2: "A partir de los datos obtenidos, desarrollamos presupuestos inteligentes y actualizables, que permanecen conectados al modelo a lo largo del ciclo de vida del proyecto. Esto permite que cualquier cambio en el diseño se refleje automáticamente en las estimaciones de costos, promoviendo un mayor control y transparencia en las inversiones.",
    service4Bloc1Title: "Modelos preparados para medición automatizada",
    service4Bloc1Text: "Uso de parámetros, filtros y codificaciones que facilitan la segmentación y agrupación de elementos según la lógica presupuestaria.",
    service4Bloc2Title: "Presupuestos dinámicos y conectados al BIM",
    service4Bloc2Text: "Actualizaciones automáticas de las cantidades en caso de cambios en el proyecto, garantizando agilidad y precisión en la revisión de costos.",
    service4Bloc3Title: "Rastreabilidad total",
    service4Bloc3Text: "Cada ítem presupuestado está vinculado directamente a elementos del modelo, permitiendo auditorías, simulaciones y toma de decisiones basada en datos consistentes.",
    service4Bloc4Title: "Compatibilidad con plataformas de presupuesto y control",
    service4Bloc4Text: "Exportamos los datos a softwares como Excel, Power BI y herramientas de costo y planificación adoptadas por el cliente.",
    service5Title: "Escaneo Láser y Modelado As-Built",
    service5Text: "Utilizamos tecnología de escaneo láser 3D de última generación para capturar con precisión milimétrica las condiciones reales de su construcción. A partir de estos datos, desarrollamos modelos digitales inteligentes (Scan to BIM) que reflejan fielmente el estado actual del edificio o infraestructura.",
    service5Text2: "Realizamos modelado 3D a partir de nubes de puntos, garantizando alta fidelidad a la obra existente. Este enfoque permite la creación de modelos digitales precisos y actualizados, ideales para retrofit, documentación as-built y gestión de activos.",
    service5Bloc1Title: "Levantamiento preciso y no invasivo",
    service5Bloc1Text: "Captura millones de puntos por segundo, reduciendo la necesidad de visitas al sitio y eliminando errores de medición manual.",
    service5Bloc2Title: "Base para retrofit, mantenimiento y expansión",
    service5Bloc2Text: "Ideal para construcciones existentes que necesitan actualización de documentación, planificación de obras de intervención o análisis de viabilidad.",
    service5Bloc3Title: "Apoyo a la toma de decisiones técnicas",
    service5Bloc3Text: "Acceso a información visual y confiable sobre el estado actual de la construcción para respaldar decisiones estratégicas.",
    service6Title: "Consultoría y Capacitación",
    service6Text: "Apoyamos a las empresas en la implementación, estructuración y evolución de la metodología BIM, ofreciendo una consultoría estratégica que integra tecnología, personas y procesos. Trabajamos junto a su equipo para transformar el BIM en una verdadera ventaja competitiva, alineada con los objetivos del negocio y las necesidades del proyecto.",
    service6Text2: "Además de la consultoría técnica, ofrecemos capacitaciones personalizadas que preparan a profesionales de distintos niveles — desde la dirección hasta la operación — promoviendo autonomía, alineación y eficiencia en la adopción de nuevas herramientas y flujos de trabajo.",
    service6Bloc1Title: "Diagnóstico de madurez BIM",
    service6Bloc1Text: "y definición del roadmap de implementación.",
    service6Bloc2Title: "Creación de directrices y planes de ejecución BIM (BEP/PEB)",
    service6Bloc2Text: "alineados con la realidad de la empresa y de los proyectos.",
    service6Bloc3Title: "Definición de procesos y flujos de información",
    service6Bloc3Text: "entre áreas como ingeniería, planificación, suministros y obra.",
    service6Bloc4Title: "Capacitaciones prácticas y estratégicas",
    service6Bloc4Text: "presenciales u online, enfocadas en herramientas, procesos y toma de decisiones basada en modelos.",
    service6Bloc5Title: "Apoyo continuo en la evolución de la madurez BIM",
    service6Bloc6Title: "Plantillas y estándares",
    service6Bloc6Text: "Desarrollamos estándares y plantillas personalizadas para software BIM, garantizando uniformidad en la modelación, consistencia en la información y mayor eficiencia en los procesos de diseño y coordinación.",
    whoUsed: "Quién utilizó este servicio",
    service6Bloc5Text: "con seguimiento, auditoría de modelos, estandarizaciones y orientaciones técnicas.",
    clientsTitle: "Algunos de nuestros clientes y sus principales proyectos",
    clientGerdau: "Coordinación y gestión del proyecto de implementación del Shredder de Gerdau. Se está implementando un nuevo sector de reciclaje en la planta de Pindamonhangaba (SP), que contará con un equipo conocido como Shredder. Esta inversión forma parte de un programa global de expansión, con una previsión de R$ 354 millones destinados al sector de reciclaje, con el objetivo de implantar tecnologías avanzadas para la separación de materiales y reducir el impacto ambiental de las operaciones.",
    clientHead5: "Consultoría e implementación de procesos BIM para los sectores de energía, minería e infraestructura, incluyendo servicios de modelado, gestión y coordinación.",
    clienteUsiminas: "Coordinación y gestión del proyecto de modernización del Alto Horno 3 de Usiminas, ubicado en la planta de Ipatinga (MG). Fue reinaugurado oficialmente el 24 de enero de 2024, tras una amplia reforma que requirió una inversión de R$ 2,7 mil millones. Este equipo es el más grande de la empresa y representa aproximadamente el 70% de la producción de acero bruto de la unidad.",
    clienteHorizonte: "Coordinación y gestión del proyecto Araguaia Ferro Nickel – Horizonte Minerals. Se trata de un emprendimiento de minería de níquel ubicado en Conceição do Araguaia, en el sureste de Pará, Brasil, con una inversión de R$ 2,9 mil millones. Concebido para ser una de las principales minas de ferroníquel del país, el proyecto tenía como objetivo atender la creciente demanda global de níquel, especialmente para la producción de acero inoxidable y baterías de vehículos eléctricos.",
    clientDraft: "Consultoría e implementación de procesos BIM para los sectores de minería e infraestructura, con servicios de modelado, gestión y coordinación.",
    clientArcelor: "Coordinación y gestión del proyecto del nuevo laminador de perfiles de ArcelorMittal en Barra Mansa. Con una inversión de R$ 1,3 mil millones, el proyecto ampliará significativamente la capacidad productiva de la planta, atendiendo a los sectores de la construcción civil, la energía y la industria automotriz. Nuestros servicios contribuyeron a la modernización de la infraestructura industrial, promoviendo una mayor eficiencia operativa y apoyando el crecimiento sostenible de la compañía.",
    teamtTitle: "Nuestro equipo de especialistas",
    team1position: "(Director)",
    team1Text: "Especialista en BIM con amplia experiencia en la coordinación, gestión e implementación de procesos digitales en proyectos complejos y de gran escala. Ha participado en emprendimientos estratégicos como la modernización del Alto Horno 3 de Usiminas (Ipatinga/MG), implementación del Shredder de Gerdau (Pindamonhangaba/SP), laminador de perfiles de ArcelorMittal (Barra Mansa/RJ) y el Proyecto Araguaia de Horizonte Minerals (Pará), totalizando más de R$ 7 mil millones en inversiones gestionadas. Con sólida actuación en sectores como minería, siderurgia, energía y reciclaje industrial, lidera la implementación de metodologías BIM aplicadas a la modelación multidisciplinar, planificación 4D, integración con cronogramas, extracción de cantidades y soporte en la toma de decisiones. A través de consultorías prestadas a HEAD5 Engenharia, Draft Solutions, entre otras, hace posible la digitalización de proyectos con enfoque en eficiencia, trazabilidad y estandarización.",
    footerInstitutional: "Institucional",
    footerAbout: "Sobre nosotros",
    footerTeam: "Nuestro equipo",
    footerSolutions: "Soluciones",
    footerCompat: "Coordinación y Compatibilización",
    footerBim: "Modelagem BIM",
    footer4d: "Planificación y Control 4D",
    footer5d: "Cantidades y Presupuestos 5D",
    footerCloud: "Escaneo Láser y Modelado As-Built",
    footerConsulting: "Consultoría y Capacitación",
    footerLegal: "Legal",
    footerPrivacy: "Política de Privacidad",
    footerTerms: "Términos de Uso",
    footerContactTitle: "Contáctanos",
    footerPhone: "+55 (31) 98396-4334",
    footerEmail: "joao.hamacek@voxcs.com.br",
    footerCopy: "© 2025 Vox. Todos los derechos reservados.",
    learnMoreButton: "Más información",
    termsTitle: "Política de Privacidad",
    termsDescription: "Tu privacidad es importante para nosotros. Esta política explica cómo recopilamos, usamos y protegemos tu información.",
    terms1Title: "1. Aceptación de los Términos",
    terms1Text: "Al acceder o utilizar este sitio web, aceptas estos Términos de Uso y todas las leyes y regulaciones aplicables.",
    terms2Title: "2. Uso del Sitio",
    terms2Text: "Te comprometes a utilizar el sitio de manera ética y legal, respetando los derechos de Vox y de terceros.",
    terms3Title: "3. Modificaciones",
    terms3Text: "Vox puede modificar estos Términos de Uso en cualquier momento, sin previo aviso.",
    privacy1Title: "1. Recopilación de Información",
    privacy1Text: "Recopilamos información proporcionada por ti y datos de navegación para mejorar tu experiencia.",
    privacy2Title: "2. Uso de la Información",
    privacy2Text: "Utilizamos tu información solo con fines internos y no la compartimos con terceros sin tu autorización.",
    privacy3Title: "3. Seguridad",
    privacy3Text: "Adoptamos medidas de seguridad para proteger tus datos personales.",
    privacyTermsBackButton: "Volver al sitio web",
    contactTitle: "Contáctanos",
    contactText: "¿Tienes dudas, sugerencias o quieres saber más sobre nuestros servicios? Rellena el formulario abajo y nuestro equipo te responderá lo antes posible.",
    contactName: "Nombre",
    contactMail: "Correo electrónico",
    contactMessage: "Mensaje",
    contactSend: "Enviar",
    successTitle: "¡Mensaje enviado!",
    successText: "Gracias por tu contacto. Nuestro equipo te responderá en breve."
  }
};

const switchers = document.querySelectorAll('#languageSwitcher, #languageSelectHeader');

// Função para aplicar traduções
function switchLanguage(lang) {
  document.querySelectorAll('[id]').forEach(el => {
    const id = el.id;
    if (translations[lang] && translations[lang][id]) {
      el.textContent = translations[lang][id];
    }
  });

  // Armazena a escolha (opcional)
  localStorage.setItem('lang', lang);
}

// Listener para todos os switchers
switchers.forEach(switcher => {
  switcher.addEventListener('change', function () {
    const selectedLang = this.value;

    switchLanguage(selectedLang);

    // Sincroniza os outros selects
    switchers.forEach(other => {
      if (other !== this) {
        other.value = selectedLang;
      }
    });
  });
});

// Carrega idioma salvo ou padrão
const defaultLang = localStorage.getItem('lang') || 'pt';
switchLanguage(defaultLang);
switchers.forEach(sw => sw.value = defaultLang);